CSIMediaTest/Models/DatabaseAccess.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace CSIMediaTest.Models
{
    public class DatabaseAccess
    {
        private SqlConnection connection;

        private void Connection()
        {
            var conString = ConfigurationManager.ConnectionStrings["NumbersConn"].ToString();
            connection = new SqlConnection(conString);
        }

        // Add Numbers
        public bool AddNumbers(Numbers numModel)
        {
            Connection();

            var cmd = new SqlCommand("AddNumbers", connection)
            {
                CommandType = CommandType.StoredProcedure
            };

            cmd.Parameters.AddWithValue("@NumberEnties", numModel.NumberEnties);
            cmd.Parameters.AddWithValue("@IsAscending", numModel.IsAscending);
            cmd.Parameters.AddWithValue("@TimeTaken", numModel.TimeTaken);

            connection.Open();
            var successful = cmd.ExecuteNonQuery();
            connection.Close();

            if (successful >= 1)
                return true;
            else
                return false;
        }

        // Get Numbers
        public List<Numbers> GetNumbers()
        {
            Connection();

            var numbers = new List<Numbers>();
            var cmd = new SqlCommand("GetNumbers", connection)
            {
                CommandType = CommandType.StoredProcedure
            };

            var adapter = new SqlDataAdapter(cmd);
            var dt = new DataTable();

            connection.Open();
            adapter.Fill(dt);
            connection.Close();

            foreach (DataRow dr in dt.Rows)
            {
                numbers.Add(
                    new Numbers
                    {
                        Id = Convert.ToInt32(dr["Id"]),
                        NumberEnties = Convert.ToString(dr["NumberEnties"]),
                        IsAscending = Convert.ToBoolean(dr["IsAscending"]),
                        TimeTaken = Convert.ToInt64(dr["TimeTaken"])
                    }
                );
            }

            return numbers;
        }
    }
}

CSIMediaTest/Models/Numbers.cs
using System;

namespace CSIMediaTest.Models
{
    public class Numbers
    {
        public int Id { get; set; }

        public string NumberEnties { get; set; }

        public bool IsAscending { get; set; }

        public long TimeTaken { get; set; }
    }
}

CSIMediaTest/Controllers/NumbersController.cs
using CSIMediaTest.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Xml.Serialization;

namespace CSIMediaTest.Controllers
{
    public class NumbersController : Controller
    {
        // GET: Numbers
        public ActionResult Index()
        {
            var db = new DatabaseAccess();

            ModelState.Clear();

            return View(db.GetNumbers());
        }
        
        // GET: Numbers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Numbers/Create
        [HttpPost]
        public ActionResult Create(Numbers numbersModel)
        {
            try
            {
                var watch = System.Diagnostics.Stopwatch.StartNew();

                numbersModel.NumberEnties = SortNumbers(numbersModel);

                watch.Stop();

                numbersModel.TimeTaken = watch.ElapsedMilliseconds;
                
                if (ModelState.IsValid)
                {
                    var db = new DatabaseAccess();

                    if (db.AddNumbers(numbersModel))
                    {
                        ViewBag.Message = "Added successfully";
                        ModelState.Clear();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // Export to XML
        public ActionResult Export()
        {
            var db = new DatabaseAccess();
            var data = db.GetNumbers();
            var Output = new StringWriter(new StringBuilder());
            var xml = new XmlSerializer(data.GetType());
            var path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "//Numbers.xml";

            xml.Serialize(Output, data);

            using (StreamWriter file = new StreamWriter(path, true))
            {
                file.Write(Output);
            }

            return RedirectToAction("Index");
        }

        private string SortNumbers(Numbers numbersModel)
        {
            var numbers = numbersModel.NumberEnties.Split(' ').ToList();
            var intNums = numbers.Select(int.Parse).ToList();

            List<int> orderedNums;

            if (numbersModel.IsAscending)
                orderedNums = intNums.OrderBy(i => i).ToList();
            else
                orderedNums = intNums.OrderByDescending(i => i).ToList();

            return string.Join(" ", orderedNums);
        }
    }
}

CSIMediaTest/Views/Numbers/Create.cshtml
@model CSIMediaTest.Models.Numbers


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Numbers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <span class="control-label col-md-2">
                Enter your integer values separated by a space (26, -8, 122, 87)
            </span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberEnties, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberEnties, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">
                Check the box for ascending order, otherwise descending order is assumed.
            </span>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAscending)
                    @Html.ValidationMessageFor(model => model.IsAscending, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
        <h3>@ViewBag.Message</h3>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CSIMediaTest/Views/Numbers/Index.cshtml
@model IEnumerable<CSIMediaTest.Models.Numbers>
<br />
<p>
    <input type="button" class="btn" value="Add Numbers" onclick="location.href='@Url.Action("Create", "Numbers")'" />
    <input type="button" class="btn" value="Export to XML in Doucments folder" onclick="location.href='@Url.Action("Export", "Numbers")'" />
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NumberEnties)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAscending)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeTaken)
        </th>
    </tr>

@foreach (var item in Model.OrderBy(i => i.TimeTaken)) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NumberEnties)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAscending)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeTaken) milliseconds
        </td>
    </tr>
}
</table>

CSIMediaTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CSI Media Code Test", "Index", "Numbers", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>